### ISSUE TITLE
Just use VM, not docker

### ISSUE THREAD

**Issue by jjangga0214** [pullreminders/slack-action#10]
This line would spend time a lot.

https://github.com/pullreminders/slack-action/blob/da2ae3e1a32c9e629f5f6fa59a95f846366e85ff/Dockerfile#L13

I tested this action in my repository, and it took around 40s.

![Screenshot from 2019-09-30 21-24-52](https://user-images.githubusercontent.com/28584151/65878325-cafc2f80-e3c8-11e9-9a96-f82ad1547a81.png)

Generally speaking, just pulling pre-built image from docker hub is a better option compared to buliding it every time the action is called.

However, I suggest not to use docker just for using curl. According to https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts, VMs already have curl preinstalled. So directly executing `entrypoint.sh` would be the best.

**Comment by lf-novelt** [comment]
I suppose docker use here helps for cross platform compatibilty (`windows-latest`)
But yeah, I noticed too the `Build pullreminders/slack-action@master` step that lasts 31sec ends up being the longest step of my workflow :'(
I'll consider switching to a JS based one that may run faster like https://github.com/marketplace/actions/action-slack

**Comment by jjangga0214** [comment]
@lf-novelt 
Yeah, docker would be help on Windows. But as Mac doesn't have it (There's an request for it though: https://github.com/actions/virtual-environments/issues/17), docker can't be the ultimate solution. 

IMHO, directly run `entrypoint.sh` on Linux, Mac, and `entrypoint(?).cmd` on Windows would be the way to go.

By the way, thanks for the JS actions suggestion, it seems it worths to be considered.

**Comment by lf-novelt** [comment]
For info, I ended doing exactly what you said: 
 - slack-send.sh
 - slack-send.ps1

```ps1
$postParams = "{'channel': '$Env:CHANNEL', 'attachments': [{'color': '$Env:COLOR', 'pretext': '$Env:PRETEXT', 'text': '$Env:TEXT'}]}"

Invoke-WebRequest -Method POST -Headers @{'Content-Type' = "application/json; charset=utf-8"; 'Authorization' = "Bearer $Env:SLACK_BOT_TOKEN"} -Uri https://slack.com/api/chat.postMessage -Body $postParams
```

callable with this syntax

```yml
    - name: Slack notification test
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_XMART_COLLAB_TOKEN }}
        CHANNEL: test-notif
        COLOR: good
        PRETEXT: Test notif windows from github
        TEXT: "<${{ github.event.commits[0].url }} |${{ github.repository }}: *${{ github.event.commits[0].message }} *> by ${{ github.event.commits[0].author.name }}\\n<${{ github.event.commits[0].url }}/checks|Workflow ${{ github.workflow }}>: `${{ job.status }}`"
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\workflows\slack-send.ps1
      shell: powershell
```

**Comment by jjangga0214** [comment]
@lf-novelt Great! Thank you for the sharing the Powershell script as well. This would be helpful to others as well :)

**Comment by robpc** [comment]
I just added a PR that uses the official curl docker image which cut the build time for me to about 12 seconds https://github.com/pullreminders/slack-action/pull/17

**Comment by jjangga0214** [comment]
@robpc Good to hear the improvement. 
However, should the action really be built every time it's used?
I still think just pulling a pre-built image can be faster, though not tested by myself.

Like by this configuration in `action.yml`. (The repo currently does not have `action.yml`).

```yaml
runs:
  using: 'docker'
  image: 'docker://pullreminders/slack-action'
```

Refer to [container-action getting started docs](https://help.github.com/en/actions/building-actions/creating-a-docker-container-action) or [reference](https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions#image) in case you're not familar with this yet.
