### ISSUE TITLE
Using Env variables on the message

### ISSUE THREAD

**Issue by joecohens** [pullreminders/slack-action#2]
Hey @abinoda thank you creating this action! I wanted to know if you have successfully used it with env variables on the message like the `$GITHUB_ACTOR` and `$GITHUB_REPOSITORY` that github provides to create dynamic messages?

e.g. `{\"channel\":\"123243434\",\"text\":\"$GITHUB_ACTOR just pushed to $GITHUB_REPOSITORY\"}`

**Comment by abinoda** [comment]
@joecohens I have, but I need to update the README and some of the setup instructions to make it easy to do this. I created https://github.com/pullreminders/slack-action/issues/1 for this. I can try to get to this in the next week or two!

**Comment by joecohens** [comment]
@abinoda that's great! I'm closing this issue in favor to #1 looking forward to it!

**Comment by dalezak** [comment]
Hmm, I can't get environment variables to work in the Slack message, it outputs:

> Issue Closed $ISSUE_TITLE $ISSUE_LABELS

I'd like to post a Slack message when a GitHub issues is closed, here's my action.

```
name: Issue Closed
on: 
  issues: 
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log("Issue", context.payload.issue)
          context.payload.issue.title >> "/github/home/issue_title.txt"
          context.payload.issue.labels.join(", ") >> "/github/home/issue_labels.txt"
          context.payload.issue.html_url >> "/github/home/issue_url.txt"
    
    - name: Notify Slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        ISSUE_TITLE: $(cat /github/home/issue_title.txt)
        ISSUE_LABELS: $(cat /github/home/issue_labels.txt)
        ISSUE_URL: $(cat /github/home/issue_url.txt)
      uses: pullreminders/slack-action@master
      with:
        args: "{'channel':'MY_CHANNEL_ID','text':'*Issue Closed (Mobile)* $ISSUE_TITLE _$ISSUE_LABELS_','attachments':[{'text':'$ISSUE_URL'}]}"
```

Any idea what's wrong?
