### ISSUE TITLE
Shell problem in entrypoint file (?)

### ISSUE THREAD

**Issue by chapati23** [pullreminders/slack-action#7]
Followed the README, and it doesn't work for me, here's the problem:

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/117495/63955583-3c248c00-ca85-11e9-9524-719513b7e67f.png">

**Link to failing job:** https://github.com/chapati23/hello-github-actions/pull/4/checks#step:3:7

My job code is as follows:

```yml
jobs:
  slack-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"D790ZUYJH\",\"text\":\"Hello world\"}'
```

Not 100% sure but this looks like some shell/bash syntax issue.

Any idea what's going wrong here?
